[app]
title = Console Proxy
package.name = consoleproxy
package.domain = org.bedrock

source.dir = .
source.include_exts = py,html,json

version = 1.0
requirements = python3,requests

orientation = portrait
fullscreen = 0

android.permissions = INTERNET, ACCESS_NETWORK_STATE
android.accept_sdk_license = True
